# Generated by Django 4.2.6 on 2024-04-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_reason', models.CharField(max_length=100)),
                ('project_type', models.CharField(max_length=100)),
                ('project_division', models.CharField(max_length=100)),
                ('project_category', models.CharField(max_length=100)),
                ('project_priority', models.CharField(max_length=100)),
                ('project_department', models.CharField(max_length=100)),
                ('project_start_date', models.CharField(max_length=100)),
                ('project_end_date', models.CharField(max_length=100)),
                ('project_location', models.CharField(max_length=100)),
                ('project_status', models.CharField(max_length=100)),
            ],
        ),
    ]
